In [0]:
from sklearn.neighbors import KNeighborsClassifier

from sklearn.datasets import fetch_openml
import numpy as np
mnist = fetch_openml('mnist_784',version=1)


In [0]:
X,Y = mnist.data, mnist.target
Y= Y.astype(np.uint8)
X_train,Y_train,X_test,Y_test = X[:60000],Y[:60000],X[60000:],Y[60000:]

In [0]:
Y_train_large = Y_train>=7
Y_train_odd = Y_train%2==1
Y_multilabel = np.c_[Y_train_large,Y_train_odd]
#Y_train_large.shape
Y_multilabel

array([[False,  True],
       [False, False],
       [False, False],
       ...,
       [False,  True],
       [False, False],
       [ True, False]])

In [0]:
knn_clf = KNeighborsClassifier()
knn_clf.fit(X_train,Y_multilabel)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [0]:
knn_clf.predict([X_train[3]])

array([[False,  True]])

In [0]:
from sklearn.model_selection import cross_val_predict
#Y_train_knn_pred = cross_val_predict(knn_clf,X_train,Y_multilabel,cv=3)

In [0]:
Y_train_knn_pred

array([[False,  True],
       [False, False],
       [False, False],
       ...,
       [False,  True],
       [False, False],
       [ True, False]])

array([[False,  True],
       [False, False],
       [False, False],
       ...,
       [False,  True],
       [False, False],
       [ True, False]])

In [0]:
from sklearn.metrics import f1_score
f1_score(Y_multilabel, Y_train_knn_pred,average='macro')

0.976410265560605

0.976410265560605